### ISSUE TITLE
Can not run example, possibly event loop policy issue

### ISSUE THREAD

**Issue by smlrcheck** [acroz/asyncio-example#1]
I've tried to run the example as in the description. I'm using Python 3.7 and got error as below. I've googled a bit and it seems like event loop policy issue but I am not 100% sure. 

(venv) C:\PycharmProjects\asyncio-example>python agent.py "sleep 3" http://localhost:5000
params: ['sleep', '3']
Traceback (most recent call last):
  File "agent.py", line 86, in <module>
    cli()
  File "agent.py", line 82, in cli
    asyncio.run(main(command_parts, args.tracking_url, args.heartbeat_period))
  File "C:\Program Files\Python37\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python37\lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "agent.py", line 55, in main
    final_status = await run(command)
  File "agent.py", line 18, in run
    process = await asyncio.create_subprocess_exec(*command)
  File "C:\Program Files\Python37\lib\asyncio\subprocess.py", line 217, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "C:\Program Files\Python37\lib\asyncio\base_events.py", line 1516, in subprocess_exec
    bufsize, **kwargs)
  File "C:\Program Files\Python37\lib\asyncio\base_events.py", line 444, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

**Comment by acroz** [comment]
Hmm, looks likely that this is due to running on Windows - I have only tested this on Unix. In the [asyncio documentation](https://docs.python.org/3/library/asyncio-subprocess.html), it says:

> The default asyncio event loop implementation on Windows does not support subprocesses. Subprocesses are available for Windows if a ProactorEventLoop is used. See Subprocess Support on Windows for details.

It looks like on Windows, on Python 3.7 and earlier, you need to configure asyncio to use a different event loop:

https://docs.python.org/3.7/library/asyncio-platforms.html#subprocess-support-on-windows

If you set this event loop policy in `agent.py`, does it fix the issue? If so, I will add a note to the README.
